volumes:
  postgres_data:
    driver: local

services:
  postgres:
    # this DB will host the keycloak config
    image: postgres:16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    restart: always
    environment:
      KC_DB_URL_HOST: "postgres"
      KC_DB_URL_DATABASE: "keycloak"
      KC_DB_URL_PORT: "5432"
      KC_METRICS_ENABLED: "true"
      KC_DB_USERNAME: pgadmin
      KC_DB_PASSWORD: pgpassword
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: INFO
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - ./keycloak/config:/opt/keycloak/data/import
      - ./keycloak/providers:/opt/keycloak/providers
    command: "start --import-realm --http-enabled=true --http-port=8080 --hostname-strict=false --optimized"
  proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    restart: always
    # see https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview
    environment:
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_CLIENT_ID: oauth2-proxy
      OAUTH2_PROXY_CLIENT_SECRET: "9htf4MohQEbbo64lcijfVvzw9Klgjfg5"
      OAUTH2_PROXY_REDIRECT_URL: "http://proxy:3000/oauth2/callback"
      OAUTH2_PROXY_OIDC_ISSUER_URL: "http://keycloak:8080/realms/app-realm"
      OAUTH2_PROXY_COOKIE_SECRET: 580b11331e148cacf8428190758c4fe2
      OAUTH2_PROXY_COOKIE_SECURE: false # for local env only
      OAUTH2_PROXY_SHOW_DEBUG_ON_ERROR: true # for local env only
      OAUTH2_PROXY_EMAIL_DOMAINS: "*" # allow any email
      OAUTH2_PROXY_UPSTREAMS: "http://front:8080/"
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      OAUTH2_PROXY_BANNER: "Login to keycloak to access the app"
      OAUTH2_PROXY_FOOTER: "SocialGouv"
      OAUTH2_PROXY_CUSTOM_SIGN_IN_LOGO: "https://socialgouv.github.io/support/img/marianne.jpeg"
    ports:
      - 3000:4180

  # this service is not exposed directly bu behind oauth2-proxy
  front:
    image: pengbai/docker-supermario
    restart: always
